version: "3.7"
services:
  # web:
  #   image: express
  #   environment: 
  #     CONNECTION_STRING: "postgresql://postgres:postgres@db:5432/my-db"
  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: my-db