# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: TerralanesAPI
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  stage: dev

plugins:
  - serverless-offline-local-authorizers-plugin
  - serverless-offline

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:

# Search
  search:
    handler:
      ./handlers/search.search
    events:
        - http:
            path: api/search
            method: get
            headers:
              - Authorization
  searchLedger:
    handler:
      ./handlers/search.searchLedger
    events:
        - http:
            path: api/ledger/search
            method: get
            headers:
              - Authorization
  searchUsersInBrokerage:
    handler:
      ./handlers/search.searchUsersInBrokerage
    events:
        - http:
            path: api/search/users
            method: get
            headers:
              - Authorization
  searchContacts:
    handler:
      ./handlers/search.searchContacts
    events:
        - http:
            path: api/search/contacts
            method: get
            headers:
              - Authorization

# Ledger
  getLedger:
    handler:
      ./handlers/ledger.getLedger
    events:
        - http:
            path: api/ledger/{id}
            method: get
            headers:
              - Authorization
              
  writeMessage:
    handler:
      ./handlers/ledger.writeMessage
    events:
        - http:
            path: api/ledger
            method: post
            headers:
              - Authorization
  deleteMessage:
    handler:
      ./handlers/ledger.deleteMessage
    events:
        - http:
            path: api/ledger/message/{id}
            method: delete
            headers:
              - Authorization
  editMessage:
    handler:
      ./handlers/ledger.editMessage
    events:
        - http:
            path: api/ledger/message/{id}
            method: put
            headers:
              - Authorization

# User
  getUser:
    handler:
      ./handlers/user.getUser
    events:
        - http:
            path: api/user
            method: get
            headers:
              - Authorization
  getUserById:
    handler:
      ./handlers/user.getUserById
    events:
        - http:
            path: api/user/{id}
            method: get
            headers:
              - Authorization
  getTeams:
    handler:
      ./handlers/user.getTeams
    events:
        - http:
            path: api/user/teams
            method: get
            headers:
              - Authorization
  createProfile:
    handler:
      ./handlers/user.createProfile
    events:
        - http:
            path: api/user
            method: post
  updateProfile:
    handler:
      ./handlers/user.updateProfile
    events:
        - http:
            path: api/user
            method: put
            headers:
              - Authorization
  getTopCustomersForUser:
    handler:
      ./handlers/user.getTopCustomersForUser
    events:
        - http:
            path: api/customer/top/{userId}
            method: get
            headers:
              - Content-Type
              - Authorization
  getTopLanesForUser:
    handler:
      ./handlers/user.getTopLanesForUser
    events:
        - http:
            path: api/lane/top/{userId}
            method: get
            headers:
              - Authorization


# Customer
  updateCustomer:
    handler:
      ./handlers/customer.updateCustomer
    events:
        - http:
            path: api/customer/{customerId}
            method: put
            headers:
              - Authorization
  getCustomer:
    handler:
      ./handlers/customer.getCustomer
    events:
        - http:
            path: api/customer/{customerId}
            method: get
            headers:
              - Content-Type
              - Authorization
  getLanesForCustomer:
    handler:
      ./handlers/customer.getLanesForCustomer
    events:
        - http:
            path: api/lanes/customer/{customerId}
            method: get
            headers:
              - Content-Type
              - Authorization
  getLocationsForCustomer:
    handler:
      ./handlers/customer.getLocationsForCustomer
    events:
        - http:
            path: api/customer/{customerId}/locations
            method: get
            headers:
              - Content-Type
              - Authorization
  getTeammatesForCustomer:
    handler:
      ./handlers/customer.getTeammatesForCustomer
    events:
        - http:
            path: api/customer/{customerId}/teammates
            method: get
            headers:
              - Authorization
  addTeammateToCustomer:
    handler:
      ./handlers/customer.addTeammateToCustomer
    events:
        - http:
            path: api/customer/teammates
            method: post
            headers:
              - Authorization
  deleteTeammateFromCustomer:
    handler:
      ./handlers/customer.deleteTeammateFromCustomer
    events:
        - http:
            path: api/customer/teammates
            method: delete
            headers:
              - Authorization

# Lane
  getLanesByUser:
    handler:
      ./handlers/lane.getLanesByUser
    events:
        - http:
            path: api/lane/user/{id}
            method: get
            headers:
              - Authorization
  getLaneById:
    handler:
      ./handlers/lane.getLaneById
    events:
        - http:
            path: api/lane/{laneId}
            method: get
            headers:
              - Authorization
  updateLane:
    handler:
      ./handlers/lane.updateLane
    events:
        - http:
            path: api/lane/{laneId}
            method: put
            headers:
              - Authorization
              - Content-Type
  getMarketFeedback:
    handler:
      ./handlers/lane.getMarketFeedback
    events:
        - http:
            path: api/lane/{laneId}/feedback
            method: get
            headers:
              - Authorization
  addMarketFeedback:
    handler:
      ./handlers/lane.addMarketFeedback
    events:
        - http:
            path: api/lane/{laneId}/feedback
            method: post
            headers:
              - Authorization
  deleteMarketFeedback:
    handler:
      ./handlers/lane.deleteMarketFeedback
    events:
        - http:
            path: api/lane/{laneId}/feedback/{feedbackId}
            method: delete
            headers:
              - Authorization
  getTeammatesForLane:
    handler:
      ./handlers/lane.getTeammatesForLane
    events:
        - http:
            path: api/lane/{laneId}/teammates
            method: get
            headers:
              - Authorization
  addTeammatetoLane:
    handler:
      ./handlers/lane.addTeammateToLane
    events:
        - http:
            path: api/lane/teammates
            method: post
            headers:
              - Authorization
  deleteTeammateFromLane:
    handler:
      ./handlers/lane.deleteTeammateFromLane
    events:
        - http:
            path: api/lane/teammates
            method: delete
            headers:
              - Authorization
  getTopCarriers:
    handler:
      ./handlers/lane.getTopCarriers
    events:
        - http:
            path: api/lane/{laneId}/carriers
            method: get
            headers:
              - Authorization

  # Team
  addTeam:
    handler:
      ./handlers/team.addTeam
    events:
        - http:
            path: api/team
            method: post
            headers:
              - Authorization
  getTeamById: 
    handler:
      ./handlers/team.getTeamById
    events:
        - http:
            path: api/team/{teamId}
            method: get
            headers:
              - Authorization
  getLanesForTeam:
    handler:
      ./handlers/team.getLanesForTeam
    events:
        - http:
            path: api/team/{teamId}/lanes
            method: get
            headers:
              - Authorization
  getTeammatesForTeam:
    handler:
      ./handlers/team.getTeammatesForTeam
    events:
        - http:
            path: api/team/{teamId}/teammates
            method: get
            headers:
              - Authorization

  # Location
  getLocationById:
    handler:
      ./handlers/location.getLocationById
    events:
        - http:
            path: api/location/{id}
            method: get
  editLocation:
    handler:
      ./handlers/location.editLocation
    events:
        - http:
            path: api/location
            method: put
  getLanesForLocation:
    handler:
      ./handlers/location.getLanesForLocation
    events:
        - http:
            path: api/location/{id}/lanes
            method: get
  getTeammatesForLocation:
    handler:
      ./handlers/location.getTeammatesForLocation
    events:
        - http:
            path: api/location/{locationId}/teammates
            method: get
            headers:
              - Authorization
  addTeammatetoLocation:
    handler:
      ./handlers/location.addTeammateToLocation
    events:
        - http:
            path: api/location/teammates
            method: post
            headers:
              - Authorization
  deleteTeammateFromLocation:
    handler:
      ./handlers/location.deleteTeammateFromLocation
    events:
        - http:
            path: api/location/teammates
            method: delete
            headers:
              - Authorization
  
  # Brokerage
  getBrokerage:
    handler:
      ./handlers/brokerage.getBrokerage
    events:
        - http:
            path: api/brokerage/{brokerageId}
            method: get
            headers:
              - Authorization
  getLanesForBrokerage:
    handler:
      ./handlers/brokerage.getLanesForBrokerage
    events:
        - http:
            path: api/brokerage/{brokerageId}/lanes
            method: get
            headers:
              - Authorization

  # Tag
  getTags:
    handler:
      ./handlers/tag.getTags
    events:
        - http:
            path: api/tag/{itemId}
            method: get
  addTag:
    handler:
      ./handlers/tag.addTag
    events:
        - http:
            path: api/tag/{itemId}
            method: post
  deleteTag:
    handler:
      ./handlers/tag.deleteTag
    events:
        - http:
            path: api/tag
            method: delete
  # Contact
  getContacts:
    handler:
      ./handlers/contact.getContacts
    events:
        - http:
            path: api/contact/{itemId}
            method: get
  addContact:
    handler:
      ./handlers/contact.addContact
    events:
        - http:
            path: api/contact/{itemId}
            method: post
  editContact:
    handler:
      ./handlers/contact.editContact
    events:
        - http:
            path: api/contact/{contactId}
            method: put
  deleteContact:
    handler:
      ./handlers/contact.deleteContact
    events:
        - http:
            path: api/contact
            method: delete

  # CSV Upload
  ascendLoadsUpload:
    handler:
      ./handlers/upload.ascendLoadsUpload
    events:
        - http:
            path: api/upload/ascend
            method: post
  ascendCustomerUpload:
    handler:
      ./handlers/upload.ascendCustomerUpload
    events:
        - http:
            path: api/upload/ascend/customers
            method: post