# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

org: terralanes
app: terralanes-backend
service: terralanes-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X" test

provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${param:SECURITY_GROUP_ID, env:SECURITY_GROUP_ID}
    subnetIds:
      - subnet-03086cdd9e1e48134
      - subnet-0243c1302f458775f
      - subnet-016928dcc4b9cba7b
  profile: default
  region: us-east-1
  stage: dev
  environment:
    DB_URL: ${param:DB_URL, env:DB_URL}
    DB_HOST: ${param:DB_HOST, env:DB_HOST}
    DB_DATABASE: ${param:DB_DATABASE, env:DB_DATABASE}
    DB_PASSWORD: ${param:DB_PASSWORD, env:DB_PASSWORD}
    DB_USERNAME: ${param:DB_USERNAME, env:DB_USERNAME}
    SEARCH_URL: ${param:SEARCH_URL, env:SEARCH_URL}
    REACT_APP_MAPBOX_KEY: ${param:REACT_APP_MAPBOX_KEY, env:REACT_APP_MAPBOX_KEY}
    NODE_ENV: ${param:NODE_ENV, env:NODE_ENV}
    ORIGIN_URL: ${param:ORIGIN_URL, env:ORIGIN_URL}
    SES_ACCESS_KEY_ID: ${param:SES_ACCESS_KEY_ID, env:SES_ACCESS_KEY_ID}
    SES_SECRET_ACCESS_KEY: ${param:SES_SECRET_ACCESS_KEY, env:SES_SECRET_ACCESS_KEY}

plugins:
  - serverless-offline
  - serverless-plugin-warmup
  - serverless-dependson-plugin
  - serverless-prune-plugin

custom:
  dependsOn:
    enabled: true
    chains: 20
  prune:
    automatic: true
    number: 3
  warmup:
    test:
      # enabled: ${param:WARMUP_ENABLED, false}
      vpc:
        securityGroupIds:
          - ${param:SECURITY_GROUP_ID, env:SECURITY_GROUP_ID}
        subnetIds:
          - subnet-03086cdd9e1e48134
          - subnet-0243c1302f458775f
          - subnet-016928dcc4b9cba7b

package:
  individually: false
  exclude:
    - data/**
    - tests/**
    - seeders/**
    - migrations/**

functions:

# Search
  search:
    # warmup: true,
    handler:
      ./handlers/search.search
    events:
        - http:
            path: api/search
            method: get
            cors: true
  searchLedger:
    # warmup: true,
    handler:
      ./handlers/search.searchLedger
    events:
        - http:
            path: api/ledger/search
            method: get
            cors: true
  searchUsersInBrokerage:
    # warmup: true,
    handler:
      ./handlers/search.searchUsersInBrokerage
    events:
        - http:
            path: api/search/users
            method: get
            cors: true
  searchContacts:
    # warmup: true,
    handler:
      ./handlers/search.searchContacts
    events:
        - http:
            path: api/search/contacts
            method: get
            cors: true

# Ledger
  getLedger:
    # warmup: true,
    handler:
      ./handlers/ledger.getLedger
    events:
        - http:
            path: api/ledger/{id}
            method: get
            cors: true
  writeMessage:
    # warmup: true,
    handler:
      ./handlers/ledger.writeMessage
    events:
        - http:
            path: api/ledger
            method: post
            cors: true
  updateMessage:
    # warmup: true,
    handler:
      ./handlers/ledger.updateMessage
    events:
        - http:
            path: api/ledger/message/{id}
            method: put
            cors: true
        - http:
            path: api/ledger/message/{id}
            method: delete
            cors: true

# User
  getUser:
    warmup: 
      test:
        enabled: ${param:WARMUP_ENABLED, false}
    handler:
      ./handlers/user.getUser
    events:
        - http:
            path: api/user
            method: get
            cors: true
  deleteUser:
    # warmup: true,
    handler:
      ./handlers/user.deleteUser
    events:
        - http:
            path: api/user/{userId}
            method: delete
            cors: true
  updateUser:
    # warmup: true,
    handler:
      ./handlers/user.updateUser
    events:
        - http:
            path: api/user/{userId}
            method: put
            cors: true
  getUserById:
    # warmup: true,
    handler:
      ./handlers/user.getUserById
    events:
        - http:
            path: api/user/{userId}
            method: get
            cors: true
  getTeams:
    # warmup: true,
    handler:
      ./handlers/user.getTeams
    events:
        - http:
            path: api/user/teams
            method: get
            cors: true
  createProfile:
    # warmup: true,
    handler:
      ./handlers/user.createProfile
    events:
        - http:
            path: api/user
            method: post
            cors: true
  updateProfile:
    # warmup: true,
    handler:
      ./handlers/user.updateProfile
    events:
        - http:
            path: api/user
            method: put
            cors: true
  getTopCustomersForUser:
    # warmup: true,
    handler:
      ./handlers/user.getTopCustomersForUser
    events:
        - http:
            path: api/customer/top/{userId}
            method: get
            cors: true
  getTopLanesForUser:
    # warmup: true,
    handler:
      ./handlers/user.getTopLanesForUser
    events:
        - http:
            path: api/lane/top/{userId}
            method: get
            cors: true

# Customer
  updateCustomer:
    # warmup: true,
    handler:
      ./handlers/customer.updateCustomer
    events:
        - http:
            path: api/customer/{customerId}
            method: put
            cors: true
  getCustomer:
    # warmup: true,
    handler:
      ./handlers/customer.getCustomer
    events:
        - http:
            path: api/customer/{customerId}
            method: get
            cors: true
  getLanesForCustomer:
    # warmup: true,
    handler:
      ./handlers/customer.getLanesForCustomer
    events:
        - http:
            path: api/lanes/customer/{customerId}
            method: get
            cors: true
  getLocationsForCustomer:
    # warmup: true,
    handler:
      ./handlers/customer.getLocationsForCustomer
    events:
        - http:
            path: api/customer/{customerId}/locations
            method: get
            cors: true
  getTeammatesForCustomer:
    # warmup: true,
    handler:
      ./handlers/customer.getTeammatesForCustomer
    events:
        - http:
            path: api/customer/{customerId}/teammates
            method: get
            cors: true
  addTeammateToCustomer:
    # warmup: true,
    handler:
      ./handlers/customer.addTeammateToCustomer
    events:
        - http:
            path: api/customer/teammates
            method: post
            cors: true
  deleteTeammateFromCustomer:
    # warmup: true,
    handler:
      ./handlers/customer.deleteTeammateFromCustomer
    events:
        - http:
            path: api/customer/teammates
            method: delete
            cors: true

# Lane
  getLanesByUser:
    # warmup: true,
    handler:
      ./handlers/lane.getLanesByUser
    events:
        - http:
            path: api/lane/user/{id}
            method: get
            cors: true
  getLaneById:
    # warmup: true,
    handler:
      ./handlers/lane.getLaneById
    events:
        - http:
            path: api/lane/{laneId}
            method: get
            cors: true
  updateLane:
    # warmup: true,
    handler:
      ./handlers/lane.updateLane
    events:
        - http:
            path: api/lane/{laneId}
            method: put
            cors: true
  getMarketFeedback:
    # warmup: true,
    handler:
      ./handlers/lane.getMarketFeedback
    events:
        - http:
            path: api/lane/{laneId}/feedback
            method: get
            cors: true
  addMarketFeedback:
    # warmup: true,
    handler:
      ./handlers/lane.addMarketFeedback
    events:
        - http:
            path: api/lane/{laneId}/feedback
            method: post
            cors: true
  deleteMarketFeedback:
    # warmup: true,
    handler:
      ./handlers/lane.deleteMarketFeedback
    events:
        - http:
            path: api/lane/{laneId}/feedback/{feedbackId}
            method: delete
            cors: true
  getTeammatesForLane:
    # warmup: true,
    handler:
      ./handlers/lane.getTeammatesForLane
    events:
        - http:
            path: api/lane/{laneId}/teammates
            method: get
            cors: true
  addTeammatetoLane:
    # warmup: true,
    handler:
      ./handlers/lane.addTeammateToLane
    events:
        - http:
            path: api/lane/teammates
            method: post
            cors: true
  deleteTeammateFromLane:
    # warmup: true,
    handler:
      ./handlers/lane.deleteTeammateFromLane
    events:
        - http:
            path: api/lane/teammates
            method: delete
            cors: true
  getTopCarriers:
    # warmup: true,
    handler:
      ./handlers/lane.getTopCarriers
    events:
        - http:
            path: api/lane/{laneId}/carriers
            method: get
            cors: true

  # Team
  addTeam:
    # warmup: true,
    handler:
      ./handlers/team.addTeam
    events:
        - http:
            path: api/team
            method: post
            cors: true
  editTeam:
    # warmup: true,
    handler:
      ./handlers/team.editTeam
    events:
        - http:
            path: api/team/{teamId}
            method: put
            cors: true
  deleteTeam:
    # warmup: true,
    handler:
      ./handlers/team.deleteTeam
    events:
        - http:
            path: api/team/{teamId}
            method: delete
            cors: true
  getTeamById: 
    # warmup: true,
    handler:
      ./handlers/team.getTeamById
    events:
        - http:
            path: api/team/{teamId}
            method: get
            cors: true
  getLanesForTeam:
    # warmup: true,
    handler:
      ./handlers/team.getLanesForTeam
    events:
        - http:
            path: api/team/{teamId}/lanes
            method: get
            cors: true
  getTeammatesForTeam:
    # warmup: true,
    handler:
      ./handlers/team.getTeammatesForTeam
    events:
        - http:
            path: api/team/{teamId}/teammates
            method: get
            cors: true
  removeTeammate:
    # warmup: true,
    handler:
      ./handlers/team.removeTeammate
    events:
        - http:
            path: api/team/teammate/{userId}
            method: delete
            cors: true
  addTeammate:
    # warmup: true,
    handler:
      ./handlers/team.addTeammate
    events:
        - http:
            path: api/team/teammate
            method: put
            cors: true

  # Location
  getLocationById:
    # warmup: true,
    handler:
      ./handlers/location.getLocationById
    events:
        - http:
            path: api/location/{locationId}
            method: get
            cors: true
  editLocation:
    # warmup: true,
    handler:
      ./handlers/location.editLocation
    events:
        - http:
            path: api/location
            method: put
            cors: true
  getLanesForLocation:
    # warmup: true,
    handler:
      ./handlers/location.getLanesForLocation
    events:
        - http:
            path: api/location/{locationId}/lanes
            method: get
            cors: true
  getTeammatesForLocation:
    # warmup: true,
    handler:
      ./handlers/location.getTeammatesForLocation
    events:
        - http:
            path: api/location/{locationId}/teammates
            method: get
            cors: true

  addTeammatetoLocation:
    # warmup: true,
    handler:
      ./handlers/location.addTeammateToLocation
    events:
        - http:
            path: api/location/teammates
            method: post
            cors: true
  deleteTeammateFromLocation:
    # warmup: true,
    handler:
      ./handlers/location.deleteTeammateFromLocation
    events:
        - http:
            path: api/location/teammates
            method: delete
            cors: true
  
  # Brokerage
  getBrokerage:
    # warmup: true,
    handler:
      ./handlers/brokerage.getBrokerage
    events:
        - http:
            path: api/brokerage/{brokerageId}
            method: get
            cors: true
  getUsersForBrokerage:
    # warmup: true,
    handler:
      ./handlers/brokerage.getUsersForBrokerage
    events:
        - http:
            path: api/brokerage/users
            method: get
            cors: true
  getLanesForBrokerage:
    # warmup: true,
    handler:
      ./handlers/brokerage.getLanesForBrokerage
    events:
        - http:
            path: api/brokerage/{brokerageId}/lanes
            method: get
            cors: true
  editBrokerage:
    # warmup: true,
    handler:
      ./handlers/brokerage.editBrokerage
    events:
        - http:
            path: api/brokerage
            method: put
            cors: true

  # Tag
  getTags:
    # warmup: true,
    handler:
      ./handlers/tag.getTags
    events:
        - http:
            path: api/tag/{itemId}
            method: get
            cors: true
  addTag:
    # warmup: true,
    handler:
      ./handlers/tag.addTag
    events:
        - http:
            path: api/tag/{itemId}
            method: post
            cors: true
  deleteTag:
    # warmup: true,
    handler:
      ./handlers/tag.deleteTag
    events:
        - http:
            path: api/tag
            method: delete
            cors: true
  # Contact
  getContacts:
    # warmup: true,
    handler:
      ./handlers/contact.getContacts
    events:
        - http:
            path: api/contact/{itemId}
            method: get
            cors: true
  addContact:
    # warmup: true,
    handler:
      ./handlers/contact.addContact
    events:
        - http:
            path: api/contact/{itemId}
            method: post
            cors: true
  editContact:
    # warmup: true,
    handler:
      ./handlers/contact.editContact
    events:
        - http:
            path: api/contact
            method: put
            cors: true
  deleteContact:
    # warmup: true,
    handler:
      ./handlers/contact.deleteContact
    events:
        - http:
            path: api/contact
            method: delete
            cors: true

  # CSV Upload
  ascendLoadsUpload:
    # warmup: true,
    handler:
      ./handlers/upload.ascendLoadsUpload
    events:
        - http:
            path: api/upload/ascend
            method: post
            cors: true
  ascendCustomerUpload:
    # warmup: true,
    handler:
      ./handlers/upload.ascendCustomerUpload
    events:
        - http:
            path: api/upload/ascend/customers
            method: post
            cors: true
    
  # Onboarding
  createAccount:
    handler:
      ./handlers/onboarding.requestAccount
    events:
        - http:
            path: api/account
            method: post
            cors: true
  getBrokerageByUUID:
    handler:
      ./handlers/onboarding.getBrokerageByUUID
    events:
        - http:
            path: api/register/{uuid}
            method: get
            cors: true
  getTeamsForBrokerage:
    # warmup: true,
    handler:
      ./handlers/onboarding.getTeamsForBrokerage
    events:
        - http:
            path: api/onboarding/teams
            method: get
            cors: true
  getCustomersForBrokerage:
    # warmup: true,
    handler:
      ./handlers/onboarding.getCustomersForBrokerage
    events:
        - http:
            path: api/onboarding/customers
            method: get
            cors: true
  joinTeam:
    # warmup: true,
    handler:
      ./handlers/onboarding.joinTeam
    events:
        - http:
            path: api/onboarding/team/{teamId}
            method: post
            cors: true

  # Billing
  webhookHandler:
    handler:
      ./handlers/billing.webhookHandler
    events:
        - http:
            path: api/stripe-webhook
            method: post
            cors: true
  createCustomer:
    handler:
      ./handlers/billing.createCustomer
    events:
        - http:
            path: api/create-customer/{brokerageId}
            method: post
            cors: true