'use strict';

/** Generated by Serverless WarmUp Plugin at 2021-04-12T20:12:03.989Z */

const AWS = require('aws-sdk');
const lambda = new AWS.Lambda({
  apiVersion: '2015-03-31',
  region: 'us-east-1',
  httpOptions: {
    connectTimeout: 1000, // 1 second
  },
});
const functions = [
  {
    "name": "terralanes-api-test-warmup-search",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-searchLedger",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-searchUsersInBrokerage",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-searchContacts",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getLedger",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-writeMessage",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-updateMessage",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getUser",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getEmailById",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-deleteUser",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-updateUser",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getUserById",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTeams",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-createProfile",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-updateProfile",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTopCustomersForUser",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTopLanesForUser",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-updateCustomer",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getCustomer",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getLanesForCustomer",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getLocationsForCustomer",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTeammatesForCustomer",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-addTeammateToCustomer",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-deleteTeammateFromCustomer",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getLanesByUser",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getLaneById",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-updateLane",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getMarketFeedback",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-addMarketFeedback",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-deleteMarketFeedback",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTeammatesForLane",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-addTeammatetoLane",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-deleteTeammateFromLane",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTopCarriers",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-addTeam",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-editTeam",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-deleteTeam",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTeamById",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getLanesForTeam",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTeammatesForTeam",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-removeTeammate",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-addTeammate",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getLocationById",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-editLocation",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getLanesForLocation",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTeammatesForLocation",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-addTeammatetoLocation",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-deleteTeammateFromLocation",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getBrokerage",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getUsersForBrokerage",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getLanesForBrokerage",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-editBrokerage",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTags",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-addTag",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-deleteTag",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getContacts",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-addContact",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-editContact",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-deleteContact",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-createAccount",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-inviteUser",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getBrokerageByUUID",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getTeamsForBrokerage",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getCustomersForBrokerage",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-webhookHandler",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-createStripeCustomer",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-createStripeSubscription",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-getBillingDetails",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  },
  {
    "name": "terralanes-api-test-warmup-updateSubscription",
    "config": {
      "enabled": true,
      "payload": "{\"source\":\"serverless-plugin-warmup\"}",
      "concurrency": 1
    }
  }
];

function getConcurrency(func, envVars) {
  const functionConcurrency = envVars[`WARMUP_CONCURRENCY_${func.name.toUpperCase().replace(/-/g, '_')}`];

  if (functionConcurrency) {
    const concurrency = parseInt(functionConcurrency);
    console.log(`Warming up function: ${func.name} with concurrency: ${concurrency} (from function-specific environment variable)`);
    return concurrency;
  }

  if (envVars.WARMUP_CONCURRENCY) {
    const concurrency = parseInt(envVars.WARMUP_CONCURRENCY);
    console.log(`Warming up function: ${func.name} with concurrency: ${concurrency} (from global environment variable)`);
    return concurrency;
  }

  const concurrency = parseInt(func.config.concurrency);
  console.log(`Warming up function: ${func.name} with concurrency: ${concurrency}`);
  return concurrency;
}

module.exports.warmUp = async (event, context) => {
  console.log('Warm Up Start');

  const invokes = await Promise.all(functions.map(async (func) => {
    const concurrency = getConcurrency(func, process.env);

    const clientContext = func.config.clientContext !== undefined
      ? func.config.clientContext
      : func.config.payload;

    const params = {
      ClientContext: clientContext
        ? Buffer.from(`{"custom":${clientContext}}`).toString('base64')
        : undefined,
      FunctionName: func.name,
      InvocationType: 'RequestResponse',
      LogType: 'None',
      Qualifier: func.config.alias || process.env.SERVERLESS_ALIAS,
      Payload: func.config.payload
    };

    try {
      await Promise.all(Array(concurrency).fill(0).map(async () => await lambda.invoke(params).promise()));
      console.log(`Warm Up Invoke Success: ${func.name}`);
      return true;
    } catch (e) {
      console.log(`Warm Up Invoke Error: ${func.name}`, e);
      return false;
    }
  }));

  console.log(`Warm Up Finished with ${invokes.filter(r => !r).length} invoke errors`);
}